### ISSUE TITLE
Wait for image to spin up

### ISSUE THREAD

**Issue by manoadamro** [tox-dev/tox-docker#9]
Using the following config
```
[testenv]
docker =
    neo4j

dockerenv =
    NEO4J_AUTH=none
```

I get this output when I run tox:
```
...
py36 docker: run 'neo4j'
...
```
This is all good, however, when I spin up this image using `docker run ...` it takes about 10 seconds to spin up. When running it with tox-docker, it is immediate, except I can't connect to the db.
`neo4j.exceptions.ServiceUnavailable: Failed to establish connection to ('127.0.0.1', 7687) (reason 61)`

Either the image is not being spun up at all or it is trying to run the tests against a database that has not yet started.

*Update 30/10/18:*

after some adding a one-minute sleep command to the top of the tox command list, It is still raising the same error.  This suggests that the ports are not being exposed, since 1 minute should be more than enough time to start the docker image

**Comment by dcrosta** [comment]
Unlike running `docker run -P ...`, tox-docker allows docker to assign random, un-used port numbers for bound ports, in order to avoid test flakes due to the port being in use.

You should have an environment var named `NEO4J_TCP_7687` present when running tests; its value will be the port number on the outside of the container to which Neo4j's port is bound.

**Comment by manoadamro** [comment]
So, It turns out that the problem was with CircleCI. 
It won't allow me to hit a container from the primary :(

**Comment by dcrosta** [comment]
> It won't allow me to hit a container from the primary

Can you explain this a bit more? It'll help us identify things quicker if others run into this issue. I don't have much experience with CircleCI, but curious to learn!
